apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sc-nas
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: csi.trident.netapp.io
parameters:
  backendType: "ontap-nas"
  csi.storage.k8s.io/fstype: "nfs"
allowVolumeExpansion: true